---
name: "Run Python linting and testing"
on:
  pull_request:
    paths:
      - "src/**"
      - "config/**"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/*"
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install tox
        run: uv pip install --system tox
      - name: Run linting, yaml and secrets checks
        run: tox -p -e linting,yaml,detect-secrets

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install tox
        run: uv pip install --system tox

      - name: Run unit tests
        run: tox -e test-unit
