name: Run Python linting and testing
on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/*"
jobs:
  run-cli-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 tox yamllint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint code with flake8 (except spikes)
        run: |
          tox -e linting
      - name: Lint yaml code
        run: |
          tox -e yaml
      - name: Check if there are any secrets in repo
        run: |
          tox -e detect-secrets
      # - name: Upload pytest test results when activated
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pytest-results
      #     path: src/**/junit/test-results-*.xml
      #   # Use always() to always publish test results
      #   if: ${{ always() }}
